# This section does two different jobs:
"""
1. It finishes connection-level validation/security logging, and then 
2. It defines cmd_query, which is the connectior's core method for 
sending a SQL query to Snowflake
"""

# 1. Validate the backoff policy 
"""
if not isinstance(self._backoff_policy, Callable) or not isinstance(
    self._backoff_policy(), Iterator
):

This is checking that _backoff_policy is not just any function, 
but speciifically a generator function that returns an iterator. 

Why? Because retry logic usually needs something like:
    1s -> 2s -> 4s -> 8s


So snowflake expects _backoff_policy to behave like:
def policy():
    yield 1
    yield 2
    yield 4
If instead you passed a normal function returning a single 
integer or list, it would not fit the retry system.

If invalid, raise Snowflake-style error:

Error.errorhandler_wrapper(
    self,
    None,
    ProgrammingError,
    {
        "msg": "Backoff policy must be a generator function",
        "errno": ER_INVALID_BACKOFF_POLICY,
    },
)

So rather than crashing without random Python error later, the connection
fails early with a structured Snowflake error. 

Purpose: retru configuration must be valid before any network work happens
"""

# 2. Log OCSP fail-open mode
"""
if self.ocsp_fail_open:
    logger.debug(...)
This is not changing behavior here, just logging it.

What "OSCP fail open" means
    OCSP is used to check whether a TLS certificate has been revoked.

In fail-open mode:  
    - the connector still tries to check certificate revocation
    - but if the OCSP responder fails or is unreachable, the connection
    is allowed to continue

So the attitude is:
    prefer connectivity over strict revocation enforcement

This is less strict than fail-closed.

"""

# 3. Log fully disabled OCSP checks
"""
if self.disable_ocsp_checks:
    logger.debug(...)
This is even more permissive. 

It means:
    do not check certificate revocation statis at all

So the difference is:
    oscp_fail_open
    - True revocation checks, but ignore responder failures. 

    disable_ocsp_checks
    - Skip revocation checking entirely. 

This block is just making that visible in debug logs so a developer
can clearly see the connection's TLS security posture. 
"""

# 4. Start of cmd_query
"""
def cmd_query(
This is one of the most important methods in the connector. 

Its job is:
take a SQL statement + metadata
build the request payload
send it to Snowflake
process the response
update local session state
return the response

So this is basically the connector's query submission method. 

"""

# 5. Build the request payload
"""
data = {
    "sqlText": sql,
    "asyncExec": _no_results,
    "sequenceId": sequence_counter,
    "querySubmissionTime": get_time_millis(),
}

This dictionary is the JSON body sent to Snowflake:
    sqlText: The actual SQL string. 
    asyncExec: Despite the name, here it is driven by _no_results.

Meaning:
    - if _no_results is True, treat this like an asytnc/no-result submission
    - if False, normal query flow

sequenceId
    A per-request counter so Snowflake can track ordering and retries. 

querySubmissionTime
    Timestamp in milliseconds for telemetry/tracking
"""

# 6. Option DataFrame AST
"""
if dataframe_ast is not None:
    data["dataframeAst"] = dataframe_ast

This is for Snowpark/DataFrame-style quert representations. 

Instead of only sending raw SQL, Snowflake can also recove an AST-
style representation of the DataFrame operation.

So this is extra metadata for higher-level APIs. 
"""

# 7. Statement parameters
"""
if statement_params is not None:
    data["parameters"] = statement_params
These are statement-level parameters, not bind values. 

Examples might include session-like execution settings that apply 
only to this query. 

Conceptually:
    run this SQL with these per-statement options    
"""

# 8. Internal query flag
"""
if is_internal:
    data["isInternal"] = is_internal

This marks queries generated by the connector itself rather than by
the user. 

For example:
    - internal metadata queries
    - diver housekeeping queries

    
This lets snowFlake distinguish client-generated internal traffic
from user SQL
"""

# 9. Describe only mode:
"""
if describe_only:
    data["describeOnly"] = describe_only

this means: 
    do not fully execute the query; just return metadata/description

Useful when the client wants schema info without actually running 
the statement 

"""

# 10. Bind state for bulk binding
"""
if binding_stage is not None:
    data["bindStage"] = binding_stage

This is useful for bulk array binding
Instead of sending all bound values inline in the request, they
may be uploaded to a staging location and referenced here. 

So this is an optimization for large batch inserts/binds. 
"""

# 11. Bind paramters
"""
if binding_params is not None:
    data["bindings"] = binding_params


These are the actual bound values for the placeholders in the
query:

Example:
    SELECT * FROM t WHERE id = ?

with:

bindings = {"1": {"type": "FIXED", "value": "42"}}

the comment mentions this is specifically for qmark parmstyle 
"""

# 12. Include query context for normal queries
"""
if not _no_results:
    queryContext = self.get_query_context()
    data["queryContextDTO"] = queryContext

For regular queries, the connector includes query context. 

This is session/query-related metadata cached on the client side
and sent back to Snowflake to help maintain continuity across
requests.


So the idea is:
    client remebers context from prior queries
    -> sends it along with the next query

This can help with stateful optimization or execution continuity

Notice they do not do this for async/no-result submissions. 
"""

# 13. Choose cleint type string
"""
client = "sfsql_file_transfer" if is_file_transfer else "sfsql"

This labels the request type.

Normal SQL query:
    sfsql 

File transfer operation:
    sfsql_file_transfer
That helps Snowflake route/log/treat the request appropriatetly. 
"""

# 14. Debug logging 
"""
logger.debug(
    "sql=[%s], sequence_id=[%s], is_file_transfer=[%s]",
    self._format_query_for_log(data["sqlText"]),
    data["sequenceId"],
    is_file_transfer,
)

If debug logging is enabled, the connector logs:
    - formatted SQL
    - sequence id
    - whether it is a file transfer

Important detail: they use _format_query_for_log(...) instead of 
raw SQL directly, which likely exists to santize or shorten the 
SQL for safer logging. 
"""

# 15. Build request URL parameters
"""
url_parameters = {REQUEST_ID: request_id}

This adds a request UUID to the URL. 

That is useful for: 
    - idempotency
    - tracing 
    - debugging retries
Each request can be uniquely identified. 
"""

# 16. Send the request
"""
ret = self.rest.request(
    "/queries/v1/query-request?" + urlencode(url_parameters),
    data,
    client=client,
    _no_results=_no_results,
    _include_retry_params=True,
    _no_retry=_no_retry,
    timeout=timeout,
)

This is the real network call. 

It sends the request to Snowflake's query endpoint:
/queries/v1/query-request

with:   
    - the JSON payload data
    - the request UUID in the URL
    - retry metadata
    - timeout behavior 
    - client type

So this is the point where the query actually leaves the Python 
connector and goes over the network.
"""

# 17. Normalize missing response structure
"""
if ret is None:
    ret = {"data": {}}
if ret.get("data") is None:
    ret["data"] = {}

This is defensive programming. 

The rest of the method assumes ret["data"] exists, so they normalize
the response shape first. 

Purpose:
    avoid None errors later
"""

# 18. Update current connection state from the response
"""
if _update_current_object:
    data = ret["data"]
If enabled, the connector updates its own connection attributes 
based on what Snowflake says the final session state is. 

This matters because queries can change session context
"""

# Final database
"""
if "finalDatabaseName" in data and data["finalDatabaseName"] is not None:
    self._database = data["finalDatabaseName"]
If the query changed the active database, update local state

Example:
    USE DATABASE mydb
After the query, the conenctor should know the current database is 
now mydb
"""

# Final schema
"""
if "finalSchemaName" in data and data["finalSchemaName"] is not None:
    self._schema = data["finalSchemaName"]

Same idea for schema
"""

# Final warehouse
"""
if "finalWarehouseName" in data and data["finalWarehouseName"] is not None:
    self._warehouse = data["finalWarehouseName"]

If the query changed warehouse, keep the client-side connection object in sync
"""

# Final role
"""
if "finalRoleName" in data:
    self._role = data["finalRoleName"]

Same for role.

Notice they do check is not None here, so Snowflake may intentially 
return None to clear/reset the role state. 
"""

# 19. Update query context cache 
"""
if "queryContext" in data and not _no_results:
    self.set_query_context(data["queryContext"])
If Snowflake returns updated query context, the client stores it
for future requests. 

So there is a feedback loop:
    send current query context
    → receive updated query context
    → cache it
    → use it on next query

That is why the earlier initialize_query_context_cache() mattered.
"""

# 20. Retrun full response
"""
return ret

The method returns the full raw-ish response dictionary 
so higher layers can:
    build cursors
    fetch results
    inspect metadata
    handle errors
"""

# Big picture
"""
This section is the connector's core query submission pipeline. 

Flow:
    validate retry/backoff config
            ↓
    log TLS/OCSP security mode
            ↓
    build query request payload
            ↓
    include binds / statement params / query context
            ↓
    send POST to /queries/v1/query-request
            ↓
    normalize response
            ↓
    update local session state
            ↓
    cache returned query context
            ↓
    return response

The most important conceptual point is this:
    cmd_query() is where the conenction object turns from a 
    config/auth object into an actual SQL transport cleint 
"""
